[package]
name = "sloppy_auth"
version = "1.2.0"
edition = "2018"
publish = false

[dependencies]
base64 = "^0.13"
ring = "^0.16"
chrono = "^0.4"
md5 = "^0.7"
url = "^2.2"
hex = "^0.4"
log = "^0.4"

[dev-dependencies]
ureq = "^2.2"
flexi_logger = "^0.19"
